import { Routes } from '@angular/router';
import { authGuard } from './guards/auth.guard';

export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'home' },
  { path: 'home', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/home/home.module').then(m => m.HomeModule) },
  { path: '1002', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentmaster/prgstudentmaster.module').then(m => m.PrgstudentmasterModule) },
  { path: '1005', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentgroup/prgstudentgroup.module').then(m => m.PrgstudentgroupModule) },
  { path: '1006', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prggraduateprogramset/prggraduateprogramset.module').then(m => m.PrggraduateprogramsetModule) },
  { path: '1007', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentallinfo/prgstudentallinfo.module').then(m => m.PrgstudentallinfoModule) },
  { path: '1008', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgsearchstudent/prgsearchstudent.module').then(m => m.PrgsearchstudentModule) },
  { path: '4107', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentlog/prgstudentlog.module').then(m => m.PrgstudentlogModule) },
  { path: '4129', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentcapture/prgstudentcapture.module').then(m => m.PrgstudentcaptureModule) },
  { path: '1010', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentstatus/prgstudentstatus.module').then(m => m.PrgstudentstatusModule) },
  { path: '1011', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentstatusset/prgstudentstatusset.module').then(m => m.PrgstudentstatussetModule) },
  { path: '1014', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgadvisorpresent/prgadvisorpresent.module').then(m => m.PrgadvisorpresentModule) },
  { path: '1015', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgchangeofficer/prgchangeofficer.module').then(m => m.PrgchangeofficerModule) },
  { path: '1017', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudenttransfer/prgstudenttransfer.module').then(m => m.PrgstudenttransferModule) },
  { path: '1019', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentcopy/prgstudentcopy.module').then(m => m.PrgstudentcopyModule) },
  { path: '1048', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgofficertype/prgofficertype.module').then(m => m.PrgofficertypeModule) },
  { path: '1049', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgofficer/prgofficer.module').then(m => m.PrgofficerModule) },
  { path: '1050', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgsearchofficer/prgsearchofficer.module').then(m => m.PrgsearchofficerModule) },
  { path: '1064', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgaddnewstudent/prgaddnewstudent.module').then(m => m.PrgaddnewstudentModule) },
  { path: '4106', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentdocument/prgstudentdocument.module').then(m => m.PrgstudentdocumentModule) },
  { path: '4046', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgexportstudentimg/prgexportstudentimg.module').then(m => m.PrgexportstudentimgModule) },
  { path: '1073', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentpassword/prgstudentpassword.module').then(m => m.PrgstudentpasswordModule) },
  { path: '1074', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgimportpic/prgimportpic.module').then(m => m.PrgimportpicModule) },
  { path: '1077', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgexportquery/prgexportquery.module').then(m => m.PrgexportqueryModule) },
  { path: '1078', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgwebmsg/prgwebmsg.module').then(m => m.PrgwebmsgModule) },
  { path: '4666', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgtmpimpreg/prgtmpimpreg.module').then(m => m.PrgtmpimpregModule) },
  { path: '1086', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgcourse/prgcourse.module').then(m => m.PrgcourseModule) },
  { path: '1087', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgprerequisite/prgprerequisite.module').then(m => m.PrgprerequisiteModule) },
  { path: '1088', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgprogram/prgprogram.module').then(m => m.PrgprogramModule) },
  { path: '1089', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgprogramstructure/prgprogramstructure.module').then(m => m.PrgprogramstructureModule) },
  { path: '1090', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgcourseequivalent/prgcourseequivalent.module').then(m => m.PrgcourseequivalentModule) },
  { path: '1104', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgcampus/prgcampus.module').then(m => m.PrgcampusModule) },
  { path: '1105', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgdegree/prgdegree.module').then(m => m.PrgdegreeModule) },
  { path: '1106', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prglevel/prglevel.module').then(m => m.PrglevelModule) },
  { path: '1107', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgfaculty/prgfaculty.module').then(m => m.PrgfacultyModule) },
  { path: '1108', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgprogramcode/prgprogramcode.module').then(m => m.PrgprogramcodeModule) },
  { path: '1109', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgacad/prgacad.module').then(m => m.PrgacadModule) },
  { path: '1110', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgadminall/prgadminall.module').then(m => m.PrgadminallModule) },
  { path: '1116', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgprovinceconfig/prgprovinceconfig.module').then(m => m.PrgprovinceconfigModule) },
  { path: '1115', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentset/prgstudentset.module').then(m => m.PrgstudentsetModule) },
  { path: '1118', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgschoolstatus/prgschoolstatus.module').then(m => m.PrgschoolstatusModule) },
  { path: '1119', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentbyschool/prgstudentbyschool.module').then(m => m.PrgstudentbyschoolModule) },
  { path: '1120', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/prgstudentschool/prgstudentschool.module').then(m => m.PrgstudentschoolModule) },
  { path: 'sysprereport/:sysmenuid', canActivate: [authGuard], data: { breadcrumbs: true }, loadChildren: () => import('./components/sysprereport/sysprereport.module').then(m => m.SysprereportModule) },
];
