const fs = require('fs');
const path = require('path');

// โหลด .env
const envFile = path.join(__dirname, '..', '.env');
if (fs.existsSync(envFile)) {
  const lines = fs.readFileSync(envFile, 'utf8').split('\n');
  for (const line of lines) {
    const [key, ...rest] = line.split('=');
    if (key && rest.length) process.env[key.trim()] = rest.join('=').trim();
  }
}

const key = process.env.DX_LICENSE_KEY || '';
if (!key) {
  console.warn('⚠️  DX_LICENSE_KEY is not set in .env');
}

const output = `// Auto-generated by scripts/set-license.js — DO NOT COMMIT
export const licenseKey = '${key}';
`;

const outPath = path.join(__dirname, '..', 'src', 'license.ts');
fs.writeFileSync(outPath, output, 'utf8');
console.log('✅ src/license.ts generated');
